version: '3.8'

services:
  web:
    build: .
    ports:
      - "10000:80"
    environment:
      - BOT_TOKEN=your_bot_token_here
    volumes:
      - ./users.json:/var/www/html/users.json
      - ./error.log:/var/www/html/error.log